name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */6 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from a GitHub user
        uses: Platane/snk@v2.0.1
        with:
          github_user_name: sakshisaraswat09
          outputs: dist/snake.svg

      - name: Push Snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
